/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.paul.pe.cpresentacion;

/**
 *
 * @author Alumno-PB203
 */
public class Contador extends javax.swing.JPanel {

    /**
     * Creates new form Contador
     */
    public Contador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TFResultado = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Viner Hand ITC", 0, 18)); // NOI18N
        jLabel1.setText("CALCULADORA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 31, 170, 32));

        TFResultado.setFont(new java.awt.Font("Monotype Corsiva", 0, 100)); // NOI18N
        TFResultado.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TFResultado.setText("0");
        TFResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFResultadoActionPerformed(evt);
            }
        });
        jPanel1.add(TFResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 69, 393, 138));

        jButton2.setText("0");
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 580, 96, 90));

        jButton3.setText("=");
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 580, 96, 90));

        jButton1.setText(".");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 580, 96, 90));

        jButton9.setText("jButton1");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 580, 96, 90));

        jButton10.setText("2");
        jPanel1.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 480, 96, 90));

        jButton11.setText("+");
        jPanel1.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 480, 96, 90));

        jButton12.setText("3");
        jPanel1.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 480, 96, 90));

        jButton13.setText("1");
        jPanel1.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 96, 90));

        jButton14.setText("5");
        jPanel1.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 96, 90));

        jButton15.setText("-");
        jPanel1.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 380, 96, 90));

        jButton16.setText("6");
        jPanel1.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, 96, 90));

        jButton17.setText("4");
        jPanel1.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 96, 90));

        jButton18.setText("CE");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 96, 60));

        jButton19.setText("/");
        jPanel1.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 96, 60));

        jButton20.setText("C");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 96, 60));

        jButton21.setText("%");
        jPanel1.add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 96, 60));

        jButton26.setText("8");
        jPanel1.add(jButton26, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 96, 90));

        jButton27.setText("*");
        jPanel1.add(jButton27, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, 96, 90));

        jButton28.setText("9");
        jPanel1.add(jButton28, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 96, 90));

        jButton29.setText("7");
        jPanel1.add(jButton29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 96, 90));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(128, 128, 128))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TFResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFResultadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFResultadoActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TFResultado;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
