/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.paul.pe.cpresentacion;

import com.paul.pe.cmodelo.TipoDocumento;
import java.sql.SQLException;
import java.text.ParseException;

/**
 *
 * @author Alumno-PB203
 */
public class JPTipoDocumento2 extends javax.swing.JPanel {
    JPTipoDocumento2 btgd = new JPTipoDocumento2();
    TipoDocumento td = new TipoDocumento();


    /**
     * Creates new form JPTipoDocumento2
     */
    public JPTipoDocumento2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaTipoDocumento = new javax.swing.JTable();
        bntmodificar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtsigla = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtorden = new javax.swing.JTextField();
        txtfechaactualizacion = new javax.swing.JTextField();
        txtestado = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtfecharegistro = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        bnteliminardatos = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtnombre1 = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("CRUD tipo documento");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(478, 98, -1, -1));

        TablaTipoDocumento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "", "", "", ""
            }
        ));
        jScrollPane1.setViewportView(TablaTipoDocumento);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 160, -1, -1));

        bntmodificar.setText("modificar");
        jPanel1.add(bntmodificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 600, -1, -1));

        btneliminar.setText("eliminar");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btneliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 600, -1, -1));

        jLabel2.setText("fecha actualizacion");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 470, 110, 20));

        txtsigla.setText("jTextField1");
        txtsigla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsiglaActionPerformed(evt);
            }
        });
        jPanel1.add(txtsigla, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 330, 30));

        jLabel3.setText("estado");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 60, -1));

        jLabel4.setText("sigla");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 60, -1));

        jLabel5.setText("orden");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 60, -1));

        txtorden.setText("jTextField1");
        jPanel1.add(txtorden, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 330, 30));

        txtfechaactualizacion.setText("jTextField1");
        jPanel1.add(txtfechaactualizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 490, 330, 30));

        txtestado.setText("jTextField1");
        txtestado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtestadoActionPerformed(evt);
            }
        });
        jPanel1.add(txtestado, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 330, 30));

        jLabel6.setText("fecha registro");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 80, 20));

        txtfecharegistro.setText("jTextField1");
        jPanel1.add(txtfecharegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 420, 330, 30));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 320, 20));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 320, 20));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 320, 20));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 450, 320, 20));

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 520, 320, 20));

        bnteliminardatos.setText("eliminar");
        bnteliminardatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnteliminardatosActionPerformed(evt);
            }
        });
        jPanel1.add(bnteliminardatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 560, -1, -1));

        btnguardar.setText("guardar");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 560, -1, -1));

        jLabel7.setText("nombre");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 60, -1));

        txtnombre1.setText("jTextField1");
        txtnombre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombre1ActionPerformed(evt);
            }
        });
        jPanel1.add(txtnombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 330, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1132, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtsiglaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsiglaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsiglaActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btneliminarActionPerformed

    private void bnteliminardatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnteliminardatosActionPerformed
          txtestado.setText("");  // Limpia un JTextField
         txtsigla.setText("");  // Limpia un JTextField
         txtorden.setText("");  // Limpia un JTextField
         txtfechaactualizacion.setText("");  // Limpia un JTextField
         txtfecharegistro.setText("");  // Limpia un JTextField
    
    }//GEN-LAST:event_bnteliminardatosActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
    try{
        

       td.setNombre(txtestado.getText());
       td.getEstado(txtestado.getText());
       td.getSigla(txtsigla.getText());
       td.setOrden(Integer .parseInt(txtorden.getText());
       td.setFechaActualiza(txtfechaactualizacion.getText());
       btgd.agregarTipo
        
    }catch(Exception e){
    }//GEN-LAST:event_btnguardarActionPerformed
    }
    private void txtestadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtestadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtestadoActionPerformed

    private void txtnombre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombre1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombre1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaTipoDocumento;
    private javax.swing.JButton bnteliminardatos;
    private javax.swing.JButton bntmodificar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextField txtestado;
    private javax.swing.JTextField txtfechaactualizacion;
    private javax.swing.JTextField txtfecharegistro;
    private javax.swing.JTextField txtnombre1;
    private javax.swing.JTextField txtorden;
    private javax.swing.JTextField txtsigla;
    // End of variables declaration//GEN-END:variables
}
